
#Comando

#python reconocedor_automatico.py --cfg config.yaml --demo
video:
    # Camara integrada
    #fuente: '0'

    # fuente: 'rtsp://admin:abc123**@192.168.7.136'
    # Camara IP
    #fuente: 'rtsp://usuario:pass@IP:Puerto' rtsp://admin:Vt3lc4123@38.51.120.236:8061
    # fuente: 'rtsp://admin:Vt3lc4123@38.51.120.236:8061'
    fuente: 'rtsp://admin:Vt3lc4123@38.51.120.236:8062'
    # fuente: '/home/vit/Documentos/para marjory/Convalpr_Vit/veh2.mp4'
    #   fuente: 'rtsp://admin:Covv01%2A.@200.109.234.154:554/Streaming/Channels/101'
    # fuente: 'rtsp://admin:Covv01%2A.@200.109.234.154:554'

    # fuente: 'assets/carrosComprimido.mp4'

     # ''
    #Camaras operativas:
#    fuente: 'rtsp://admin:Vt3lc4123@38.51.120.236:8061'
    ## 'rtsp://admin:Vt3lc4123@38.51.120.236:8062'
    ## 'rtsp://admin:Vt3lc4123@38.51.120.236:8063'
    ## 'rtsp://admin:Vt3lc4123@38.51.120.236:8064'

    # ''

    # Video en disco
    # fuente: 'C:/Usuarios/User/Escritorio/carros.mp4'
    #  fuente: 'C:/Users/josevit/Desktop/carros.mp4'
# "C:\Users\josevit\Desktop\carros.mp4"
    # Imagen en disco
    # (usar reconocedor_automatico.py)

    # Cada cuantos Frames hacer inferencia
    # No se aplica si --demo
    frecuencia_inferencia: 30
modelo:
    # resolucion puede ser {608, 512, 384}
    resolucion_detector: 608

    # Objectness/Score de yolo
    confianza_detector: 0.25

    # Modelos {1, 2, 3, 4}
    # 3 y 4 + rapidos en CPU
    numero_modelo_ocr: 4

    # Se queda solo con aquellas patentes
    # cuyo promedio de las probabilidades de
    # los caracteres es mayor a 0.4
    confianza_avg_ocr: 0.3

    # Si algun caracter esta por debajo de
    # confianza_low_ocr, se descarta
    confianza_low_ocr: 0.10
db:
    # Guardar en SQLite
    # ( Base de datos Local )
    # (No guarda cuando se usa --demo)
    guardar: true

    # Cada cuantas patentes hacer
    # el insert en la BD
    insert_frequency: 1

    # Path de la BD
    path: 'db/plates.db'
